# App Engine configuration (alternative to Cloud Run)
runtime: python311

env_variables:
  PORT: 8080

# Automatic scaling
automatic_scaling:
  min_instances: 0
  max_instances: 100
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.65

# Resources
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

# Health check
health_check:
  enable_health_check: True
  check_interval_sec: 30
  timeout_sec: 10
  unhealthy_threshold: 2
  healthy_threshold: 2

# Network settings
network:
  forwarded_ports:
    - 8080

# Runtime settings
runtime_config:
  python_version: "3.11"
